### ISSUE TITLE
Handle byte order

### ISSUE THREAD

**Issue by simonschllng** [jfjlaros/bin-parser#2]
Is there a way to specify the byte order for integers?

**Comment by jfjlaros** [comment]
I will add an option to select big endian format.

**Comment by simonschllng** [comment]
Oh, got it. Had some trouble to find the referenced "function". Now that I found them, I see it uses little endian, what is what I need.
More important would be a float function. ;-)

**Comment by jfjlaros** [comment]
I will implement it anyway, it is bound to pop up one time or an other.

As for floats, do you have a particular case in mind?

**Comment by simonschllng** [comment]
I try to parse files which use floats: https://github.com/simonschllng/libpes/tree/master/bin-parser

**Comment by simonschllng** [comment]
And your lib is very helpful! :+1:

**Comment by jfjlaros** [comment]
If you know how to parse floats in this format, you can add a [new type](https://github.com/jfjlaros/bin-parser#defining-new-types) yourself. I would be happy to add it to the library for other people to use if you want.

Otherwise, if you have some examples of the binary- and decoded representation, I can give it a try.

**Comment by jfjlaros** [comment]
Endianness implemented in 4be66e23.
